apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: malgivonkokos
  namespace: gotk-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/malgivonkokos/notes-app